server:
  port: 8001

spring:
  application:
    name: sso-sample

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


javashitang:
  sso:
    enable: true
    includePattern: /task/getInfo,/manage/getInfo,/location/getInfo
    excludePattern:
